name: Foodie

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-11 

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app
    - name: Install Dependencies
      run: pod install --repo-update
      shell: bash
    - name: Build and test
      run: xcodebuild clean build test -workspace Foodie.xcworkspace -scheme "Foodie" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
